clients_num: 1
BLOCK_LENGTH: 1024
SH_MAX_ORDER: 2 
IR_TRUNCATION_LEVEL: -200
REMOTE_OSC_PORT: 5100
monitoring:
    name: monitoring
    starting_output_channel: 62
    output_channel_count: 2  
    osc_port: 5005
microphones: 
    - 
        name: mic1
        starting_input_channel: 2
        input_channel_count: 8
        starting_output_channel: 64
        output_channel_count: 2
        azim_deg: 0
        osc_port: 5005
        hrir_type: "HRIR_SOFA"
        hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
        hrir_delay: 0
        hrir_level: 0
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
        arir_delay: 0
        arir_level: 0
        compensation: "None"
        is_measured_encoding: True
        encoding_filter_name: "None"
        encoding_filter_type: "None"
    