clients_num: 1
BLOCK_LENGTH: 2048
SH_MAX_ORDER: 4
IR_TRUNCATION_LEVEL: -60
microphones: 
  - 
      name: mic1
      starting_input_channel: 2
      input_channel_count: 32
      starting_output_channel: 40
      output_channel_count: 2
      angle: 0
      osc_port: 5005
      hrir_type: "HRIR_SOFA"
      hrir_file: "res/HRIR/KU100_THK/48k_32bit_128tap_2702dir.sofa"
      hrir_delay: 0
      hrir_level: 0
      arir_type: "AS_MIRO"
      arir_file: "res/ARIR/RT_calib_EM32ch_struct.mat"
      arir_delay: 0
      arir_level: 0
      compensation: None