clients_num: 5
BLOCK_LENGTH: 4096
SH_MAX_ORDER: 2 
IR_TRUNCATION_LEVEL: -200
REMOTE_OSC_PORT: 5100
monitoring:
    name: monitoring
    starting_output_channel: 64
    output_channel_count: 2  
    osc_port: 7000
microphones: 
   - 
      name: mic1
      starting_input_channel: 2
      input_channel_count: 8
      starting_output_channel: 54
      output_channel_count: 2
      azim_deg: 0
      osc_port: 7000
      hrir_type: "HRIR_SOFA"
      hrir_file: "res/HRIR/KEMAR_SADIE2/D2_48K_24bit_256tap_FIR_SOFA.sofa"
      hrir_delay: 0
      hrir_level: 0
      arir_type: "AS_MIRO"
      arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
      arir_delay: 0
      arir_level: 0
      compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
      is_measured_encoding: False
      encoding_filter_name: "None"
      encoding_filter_type: "None"
   - 
      name: mic2
      starting_input_channel: 11
      input_channel_count: 8
      starting_output_channel: 56
      output_channel_count: 2
      azim_deg: 0
      osc_port: 7000
      hrir_type: "HRIR_SOFA"
      hrir_file: "res/HRIR/KU100_SADIE2/D1_48K_24bit_256tap_FIR_SOFA.sofa"
      hrir_delay: 0
      hrir_level: 0
      arir_type: "AS_MIRO"
      arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
      arir_delay: 0
      arir_level: 0
      compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
      is_measured_encoding: False
      encoding_filter_name: "None"
      encoding_filter_type: "None"
   - 
      name: mic3
      starting_input_channel: 20
      input_channel_count: 8
      starting_output_channel: 58
      output_channel_count: 2
      azim_deg: 0
      osc_port: 7000
      hrir_type: "HRIR_SOFA"
      hrir_file: "res/HRIR/KEMAR_SADIE2/D2_48K_24bit_256tap_FIR_SOFA.sofa"
      hrir_delay: 0
      hrir_level: 0
      arir_type: "AS_MIRO"
      arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
      arir_delay: 0
      arir_level: 0
      compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
      is_measured_encoding: False
      encoding_filter_name: "None"
      encoding_filter_type: "None"
   - 
      name: mic4
      starting_input_channel: 29
      input_channel_count: 8
      starting_output_channel: 60
      output_channel_count: 2
      azim_deg: 0
      osc_port: 7000
      hrir_type: "HRIR_SOFA"
      hrir_file: "res/HRIR/KEMAR_SADIE2/D2_48K_24bit_256tap_FIR_SOFA.sofa"
      hrir_delay: 0
      hrir_level: 0
      arir_type: "AS_MIRO"
      arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
      arir_delay: 0
      arir_level: 0
      compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
      is_measured_encoding: False
      encoding_filter_name: "None"
      encoding_filter_type: "None"
   - 
      name: mic5
      starting_input_channel: 38
      input_channel_count: 8
      starting_output_channel: 62
      output_channel_count: 2
      azim_deg: 0
      osc_port: 7000
      hrir_type: "HRIR_SOFA"
      hrir_file: "res/HRIR/KEMAR_SADIE2/D2_48K_24bit_256tap_FIR_SOFA.sofa"
      hrir_delay: 0
      hrir_level: 0
      arir_type: "AS_MIRO"
      arir_file: "res/ARIR/RT_calib_SM8polimi_struct_updated_no_scatter.mat"
      arir_delay: 0
      arir_level: 0
      compensation: "MODAL_RADIAL_FILTER+SPHERICAL_HEAD_FILTER"
      is_measured_encoding: False
      encoding_filter_name: "None"
      encoding_filter_type: "None"
   