clients_num: 5
BLOCK_LENGTH: 4096
microphones: 
  - 
      name: mic1
      starting_input_channel: 0
      input_channel_count: 4
      starting_output_channel: 20
      output_channel_count: 4
      angle: 0
      osc_port: 5005
  - 
      name: mic2
      starting_input_channel: 4
      input_channel_count: 4
      starting_output_channel: 24
      output_channel_count: 4
      angle: 0
      osc_port: 5015
  - 
      name: mic3
      starting_input_channel: 8
      input_channel_count: 4
      starting_output_channel: 28
      output_channel_count: 4
      angle: 0
      osc_port: 5025
  - 
      name: mic4
      starting_input_channel: 12
      input_channel_count: 4
      starting_output_channel: 32
      output_channel_count: 4
      angle: 0
      osc_port: 5035
  - 
      name: mic5
      starting_input_channel: 16
      input_channel_count: 4
      starting_output_channel: 36
      output_channel_count: 4
      angle: 0
      osc_port: 5045