clients_num: 1
BLOCK_LENGTH: 2048
SH_MAX_ORDER: 2
microphones: 
    - 
        name: mic1
        starting_input_channel: 2
        input_channel_count: 8
        starting_output_channel: 20
        output_channel_count: 9
        osc_port: 5005
        arir_type: "AS_MIRO"
        arir_file: "res/ARIR/RT_calib_SM8polimi_struct_1.mat"