microphones: 
  - name: mic1
    starting_channel: 1
    ending_channel: 8
    angle: 0
    osc_port: 5005
  - name: mic2
    starting_channel: 9
    ending_channel: 16
    angle: 0
    osc_port: 5006
  - name: mic3
    starting_channel: 17
    ending_channel: 24
    angle: 0
    osc_port: 5007
  - name: mic4
    starting_channel: 25
    ending_channel: 32
    angle: 0
    osc_port: 5008
  - name: mic5
    starting_channel: 33
    ending_channel: 40
    angle: 0
    osc_port: 5009