name: MuMiReF
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.19
  - pyfftw
  - scipy[version='>=0.16']
  - pip
  - matplotlib
  - python=3.8
  - pyserial[version='>=3.4']
  - pyyaml
